export const TODO_LIST_ITEM_INSERT = 'TODO_LIST_ITEM_INSERT';
export const TODO_LIST_ITEM_UPDATE = 'TODO_LIST_ITEM_UPDATE';
export const TODO_LIST_ITEM_DELETE = 'TODO_LIST_ITEM_DELETE';
export const TODO_LIST_ITEM_EDIT = 'TODO_LIST_ITEM_EDIT';
export const TODO_LIST_ITEM_CANCEL_EDIT = 'TODO_LIST_ITEM_CANCEL_EDIT';
export const APP_FETCH_ERROR = 'APP_FETCH_ERROR';
export const APP_FETCH_SUCCESS = 'APP_FETCH_SUCCESS';
