export const TODO_LIST_ITEM_INSERT: string = 'TODO_LIST_ITEM_INSERT';
export const TODO_LIST_ITEM_UPDATE: string = 'TODO_LIST_ITEM_UPDATE';
export const TODO_LIST_ITEM_DELETE: string = 'TODO_LIST_ITEM_DELETE';
export const TODO_LIST_ITEM_EDIT: string = 'TODO_LIST_ITEM_EDIT';
export const TODO_LIST_ITEM_CANCEL_EDIT: string = 'TODO_LIST_ITEM_CANCEL_EDIT';
