export const TODO_LIST_ITEM_CREATE = 'TODO_LIST_ITEM_CREATE';
export const TODO_LIST_ITEM_UPDATE = 'TODO_LIST_ITEM_UPDATE';
export const TODO_LIST_ITEM_DELETE = 'TODO_LIST_ITEM_DELETE';
export const TODO_LIST_ITEM_EDIT_START = 'TODO_LIST_ITEM_EDIT_START';
export const TODO_LIST_ITEM_EDIT_END = 'TODO_LIST_ITEM_EDIT_END';
