export const TODO_LIST_ITEM_INSERT = 'TODO_LIST_ITEM_INSERT';
export const TODO_LIST_ITEM_UPDATE = 'TODO_LIST_ITEM_UPDATE';
export const TODO_LIST_ITEM_DELETE = 'TODO_LIST_ITEM_DELETE';
export const TODO_LIST_ITEM_EDIT = 'TODO_LIST_ITEM_EDIT';
export const TODO_LIST_ITEM_CANCEL_EDIT = 'TODO_LIST_ITEM_CANCEL_EDIT';

export const ITEMS_FETCH_STARTED = 'ITEMS_FETCH_STARTED';
export const ITEMS_FETCH_FAILED = 'ITEMS_FETCH_FAILED';
export const ITEMS_FETCH_SUCCEEDED = 'ITEMS_FETCH_SUCCEEDED';
export const ITEM_INSERT_SUCCEEDED = 'ITEM_INSERT_SUCCEEDED';
export const ITEM_INSERT_FAILED = 'ITEM_INSERT_FAILED';
export const ITEM_DELETION_SUCCEEDED = 'ITEM_DELETION_SUCCEEDED';
export const ITEM_DELETION_FAILED = 'ITEM_DELETION_FAILED';
export const ITEM_UPDATE_SUCCEEDED = 'ITEM_UPDATE_SUCCEEDED';
export const ITEM_UPDATE_FAILED = 'ITEM_UPDATE_FAILED';

export const ITEM_ERROR_CLOSE = 'ITEM_ERROR_CLOSE';
export const ITEMS_FETCH_ERROR_CLOSE = 'ITEMS_FETCH_ERROR_CLOSE';
export const ITEM_INSERT_ERROR_CLOSE = 'ITEM_INSERT_ERROR_CLOSE';
