export const TODO_LIST_ITEM_INSERT = 'TODO_LIST_ITEM_INSERT';
export const TODO_LIST_ITEM_UPDATE = 'TODO_LIST_ITEM_UPDATE';
export const TODO_LIST_ITEM_DELETE = 'TODO_LIST_ITEM_DELETE';
export const TODO_LIST_ITEM_TOGGLE = 'TODO_LIST_ITEM_TOGGLE';
